{% set name = "rule-engine" %}
{% set version = "4.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rule-engine-{{ version }}.tar.gz
  sha256: 7c117afe090316e9be543ec14bb9e1a426d5e369dac50b4b8b82aedb6e46015c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - ply >=3.9
    - python >=3.4
    - python-dateutil >=2.7,<3

test:
  imports:
    - rule_engine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zeroSteiner/rule-engine
  summary: A lightweight, optionally typed expression language with a custom grammar for matching arbitrary Python objects.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - drbixx
    - teake
