{% set name = "rule-engine" %}
{% set version = "4.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7d6c4276ebb208362a07dca437638623e9705abb9b87e9b61a5cf7ba51fee835

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - ply >=3.9
    - python >=3.4
    - python-dateutil >=2.7,<3

test:
  imports:
    - rule_engine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zeroSteiner/rule-engine
  summary: A lightweight, optionally typed expression language with a custom grammar for matching arbitrary Python objects.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - drbixx
    - teake
