{% set name = "rule-engine" %}
{% set version = "4.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3d0215230ef0bdeb4e047331705dc772746d41161874b3639959ec76e327632f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - ply >=3.9
    - python >={{ python_min }}
    - python-dateutil >=2.7,<3

test:
  imports:
    - rule_engine
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zeroSteiner/rule-engine
  summary: A lightweight, optionally typed expression language with a custom grammar for matching arbitrary Python objects.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - drbixx
    - teake
