{% set name = "rule-engine" %}
{% set version = "4.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rule-engine-{{ version }}.tar.gz
  sha256: a358592b95316969a1e3c66fb0fdd457a2189f31891a6c1425d0308c1d6b19bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - ply >=3.9
    - python >=3.4
    - python-dateutil >=2.7,<3

test:
  imports:
    - rule_engine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zeroSteiner/rule-engine
  summary: A lightweight, optionally typed expression language with a custom grammar for matching arbitrary Python objects.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - drbixx
    - teake
